[package]
name = "stdng"
version = "0.1.4"
edition = "2021"
description = "An enhancement for Rust standard library"
license-file = "LICENSE"
repository = "https://github.com/xflops/stdng"

[dependencies]
