[package]
name = "soil"
version = "0.1.0"
edition = "2021"
description = "An enhancement for Rust standard library"
license-file = "LICENSE"
repository = "https://github.com/xflops/soil"

[dependencies]
